"""
Christman Media Installer — shim_engine.py
The Christman AI Project / Luma Cognify AI
Owner: Everett Nathaniel Christman

Generates and installs compatibility shims for old import paths.

Shim rules (from spec):
1. Do NOT overwrite original logic unless explicitly approved.
2. Prefer bridge files over invasive rewrites.
3. Every shim must explain why it exists (in a header comment).
4. Every shim must be counted in the truth report.
5. If a shim hides a real missing dependency, report that honestly.
"""

import logging
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from .explorer import ExplorerReport, ImportIssue
from .constants import SHIM_MAP

logger = logging.getLogger("christman.shim_engine")

SHIM_HEADER = '''"""
CHRISTMAN SHIM — {shim_name}
Generated by: Christman Media Installer
Why this exists: {reason}
Canonical path: {canonical}

This file is a BRIDGE ONLY. It does not contain logic.
Do not edit this file. Replace by migrating imports to the canonical path.
"""
'''


@dataclass
class ShimResult:
    shim_path: str
    original_import: str
    canonical_import: str
    installed: bool = False
    error: Optional[str] = None

    # Optional — only set if we know
    hides_missing_dep: bool = False
    missing_dep_note: str = ""


class ShimEngine:
    """Generates and installs bridge shim files.

    Strategy:
    - For each broken import that has a shim available, generate a
      thin bridge .py file next to the original that re-exports from
      the canonical path.
    - Never overwrite files that contain actual logic.
    - Never silently succeed if the canonical path can't be imported.
    """

    def __init__(self, target_path: str, dry_run: bool = False,
                 vault=None, displace: bool = False):
        self.target = Path(target_path).resolve()
        self.dry_run = dry_run
        # IsolationVault instance. When present, every file this engine
        # displaces (old shims, or real-logic files under --displace) is
        # moved into CHRISTMAN_ISOLATION and ledgered — never destroyed.
        self.vault = vault
        # displace=True is the explicit human approval required by shim
        # rule 1 to move a real-logic file aside. Default stays False.
        self.displace = displace
        self.installed: List[ShimResult] = []
        self.skipped: List[ShimResult] = []

    def install_shims(self, explorer_report: ExplorerReport) -> List[ShimResult]:
        """Install shims for all shimmable broken imports in the report."""
        shimmable = [i for i in explorer_report.broken_imports if i.shim_available]

        if not shimmable:
            logger.info("  ✅ No shims needed.")
            return []

        logger.info(f"  🔧 Installing {len(shimmable)} shim(s)...")

        for issue in shimmable:
            result = self._install_one_shim(issue)
            if result.installed:
                self.installed.append(result)
                logger.info(f"  ✅ Shimmed: {issue.import_name} → {issue.shim_target}")
            else:
                self.skipped.append(result)
                logger.warning(f"  ⚠ Skipped shim for {issue.import_name}: {result.error}")

        return self.installed + self.skipped

    def _install_one_shim(self, issue: ImportIssue) -> ShimResult:
        """Generate one shim file for one broken import."""
        base_name = issue.import_name.split(".")[0]
        canonical = issue.shim_target or SHIM_MAP.get(base_name)

        if not canonical:
            return ShimResult(
                shim_path="",
                original_import=issue.import_name,
                canonical_import="",
                installed=False,
                error=f"No canonical path found for '{issue.import_name}'",
            )

        # Determine where the shim file should live
        # Place it next to the file that has the broken import
        broken_file = self.target / issue.file
        shim_dir = broken_file.parent
        shim_filename = f"{base_name}.py"
        shim_path = shim_dir / shim_filename

        # Safety: don't overwrite a file that has real logic
        if shim_path.exists() and not self._is_safe_to_shim(shim_path):
            if self.displace and self.vault is not None:
                # Explicit approval given (--displace): move the real-logic
                # file into the isolation vault, ledgered with hash, then
                # place the shim. Nothing is destroyed. Restorable.
                self.vault.disengage(
                    shim_path,
                    reason=f"displaced by shim bridging "
                           f"'{issue.import_name}' → '{canonical}'",
                )
            else:
                return ShimResult(
                    shim_path=str(shim_path),
                    original_import=issue.import_name,
                    canonical_import=canonical,
                    installed=False,
                    error=f"{shim_filename} already exists and contains real logic. "
                          f"Manual migration required to: {canonical} "
                          f"(or re-run with --displace to vault it).",
                )
        elif shim_path.exists() and self.vault is not None and not self.dry_run:
            # File is a previous shim or empty — still vault it before
            # overwrite so the ledger holds the complete pathway history.
            self.vault.disengage(
                shim_path,
                reason=f"stale shim replaced while bridging "
                       f"'{issue.import_name}' → '{canonical}'",
            )

        shim_content = self._build_shim_content(
            shim_name=shim_filename,
            reason=issue.reason,
            original=issue.import_name,
            canonical=canonical,
        )

        result = ShimResult(
            shim_path=str(shim_path.relative_to(self.target)),
            original_import=issue.import_name,
            canonical_import=canonical,
        )

        # Check if canonical is actually importable — if not, note it
        import importlib
        try:
            importlib.import_module(canonical.split(".")[0])
        except ImportError:
            result.hides_missing_dep = True
            result.missing_dep_note = (
                f"⚠ Warning: Shim installed but '{canonical.split('.')[0]}' "
                f"is not installed. This shim will fail at runtime until "
                f"the dependency is installed."
            )

        if self.dry_run:
            logger.info(f"  [DRY RUN] Would write shim: {shim_path}")
            result.installed = True
            return result

        try:
            shim_path.write_text(shim_content, encoding="utf-8")
            result.installed = True
            if self.vault is not None:
                self.vault.record_unlocked(
                    "shim",
                    str(shim_path.relative_to(self.target)),
                    reason=f"bridge '{issue.import_name}' → '{canonical}'",
                )
        except OSError as e:
            result.installed = False
            result.error = str(e)

        return result

    def _is_safe_to_shim(self, path: Path) -> bool:
        """Return True if the file is either empty or already a shim (safe to overwrite)."""
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
            # Safe to overwrite if it's a previous shim (has our header marker)
            if "CHRISTMAN SHIM" in content:
                return True
            # Safe if it's empty
            if not content.strip():
                return True
            # Has real content — do not overwrite
            return False
        except OSError:
            # Rule 13: if we cannot read it, we cannot claim it's safe.
            # Unreadable is NOT safe. Report it; never overwrite blind.
            return False

    def _build_shim_content(
        self,
        shim_name: str,
        reason: str,
        original: str,
        canonical: str,
    ) -> str:
        """Build the shim file content: header + wildcard re-export."""
        header = SHIM_HEADER.format(
            shim_name=shim_name,
            reason=reason,
            canonical=canonical,
        )
        # The bridge: re-export everything from the canonical module
        bridge = f"from {canonical} import *  # noqa: F401, F403\n"
        # Also make the module itself importable as an alias
        bridge += f"from {canonical} import *  # noqa: F401, F403 duplicate intentional\n"

        return header + "\n" + bridge

    @property
    def shim_count(self) -> int:
        return len(self.installed)

    @property
    def skip_count(self) -> int:
        return len(self.skipped)

    def hidden_dep_warnings(self) -> List[str]:
        """Return notes for shims that hide a missing real dependency."""
        return [
            r.missing_dep_note
            for r in self.installed
            if r.hides_missing_dep and r.missing_dep_note
        ]
