"""
CHRISTMAN SHIM — logger.py
Generated by: Christman Media Installer
Why this exists: Bridge old import path 'logger' to canonical 'christman_voice_sdk.utils.logger'
Canonical path: christman_voice_sdk.utils.logger

This file is a BRIDGE ONLY. It does not contain logic.
Do not edit this file. Migrate imports to the canonical path when possible.
"""

from christman_voice_sdk.utils.logger import *  # noqa: F401, F403
